name: CI/CD

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  VERSION_UPSTREAM: 1.28.1
  VERSION_BUILD: 1

jobs:
  Variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION_UPSTREAM }}
      build: ${{ env.VERSION_BUILD }}
    steps:
      - run: echo "Expose env vars"

  ShellCheck:
    uses: ./.github/workflows/shellcheck.yml
  flavor-influxdb:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: influxdb
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.influxdb,outputs.influxdb_v2
      parsers: parsers.influx
      processors:
      serializers:
  flavor-prometheus:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: prometheus
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.prometheus_client
      parsers: parsers.influx
      processors:
      serializers:
  flavor-prometheus-loki:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: prometheus+loki
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.prometheus_client,outputs.loki
      parsers: parsers.influx
      processors:
      serializers:
  flavor-splunk:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: splunk
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.http
      parsers: parsers.influx
      processors: processors.rename
      serializers: serializers.splunkmetric
