name: Release

on:
  push:
    tags:
      - '**'

env:
  VERSION_UPSTREAM: 1.28.1
  VERSION_BUILD: 1

jobs:
  Variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION_UPSTREAM }}
      build: ${{ env.VERSION_BUILD }}
    steps:
      - run: echo "Expose env vars"

  ShellCheck:
    uses: ./.github/workflows/shellcheck.yml
  flavor-influxdb:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: influxdb
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.influxdb,outputs.influxdb_v2
      parsers: parsers.influx
      processors:
      serializers:
  flavor-prometheus:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: prometheus
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.prometheus_client
      parsers: parsers.influx
      processors:
      serializers:
  flavor-prometheus-loki:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: prometheus+loki
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.prometheus_client,outputs.loki
      parsers: parsers.influx
      processors:
      serializers:
  flavor-splunk:
    needs:
      - Variables
      - ShellCheck
    uses: ./.github/workflows/build.yml
    with:
      flavor: splunk
      version: ${{ needs.Variables.outputs.version }}
      build: ${{ needs.Variables.outputs.build }}
      inputs: inputs.bond,inputs.cpu,inputs.disk,inputs.diskio,inputs.dns_query,inputs.ethtool,inputs.exec,inputs.http_response,inputs.internal,inputs.internet_speed,inputs.iptables,inputs.mem,inputs.net,inputs.netstat,inputs.net_response,inputs.ping,inputs.processes,inputs.snmp,inputs.snmp_legacy,inputs.snmp_trap,inputs.system
      outputs: outputs.http
      parsers: parsers.influx
      processors: processors.rename
      serializers: serializers.splunkmetric
  Release:
    needs:
      - flavor-influxdb
      - flavor-prometheus
      - flavor-prometheus-loki
      - flavor-splunk
    runs-on: ubuntu-latest
    steps:
      - name: Draft
        uses: actions/create-release@v1
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mips.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mipsel.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mips.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mipsel.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mips.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mipsel.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mips.deb
          path: ./
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mipsel.deb
          path: ./
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mips.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mips.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mips.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mipsel.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mipsel.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+influxdb_mipsel.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mips.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mips.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mips.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mipsel.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mipsel.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus_mipsel.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mips.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mips.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mips.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mipsel.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mipsel.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+prometheus+loki_mipsel.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mips.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mips.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mips.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mipsel.deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mipsel.deb
          asset_name: telegraf_${{ env.VERSION_UPSTREAM }}-${{ env.VERSION_BUILD }}+splunk_mipsel.deb
          asset_content_type: application/vnd.debian.binary-package
